# Generated by Django 3.0 on 2020-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200124_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('AC', 'Academica'), ('CU', 'Cultural'), ('DE', 'Deportiva')], max_length=4, null=True),
        ),
    ]
